WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

CAPTION = "Bot Appetite"

FRAMERATE = 60

SPICY="SPICY"
SAVORY="SAVORY"
SWEET="SWEET"
SOUR="SOUR"



FLAVORS = [SPICY, SAVORY, SWEET]

FLAVOR_COLORS = {
    SPICY: (255, 0, 0),
    SAVORY: (0, 0, 255),
    SWEET: (255, 0, 255),
}

FLAVOR_NAMES = {
    SPICY: "spicy",
    SAVORY: "savory",
    SWEET: "sweet",
}

FLAVOR_ICONS = {
    SPICY: "assets/images/spicy_icon.png",
    SWEET: "assets/images/sweet_icon.png",
    SAVORY: "assets/images/savory_icon.png",
}

BAD = 0
OKAY = 1
GREAT = 2

QUEUED = 0
SPEAKING = 1
WAITING = 2
SERVED = 3

PRINTABLES = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890!@#$%^&*()-=_+,.<>/?;:' É"

ROBOT_DIALOG = (
    "DELICIOUS AND NUTRITIOUS",
    "TASTY FOOD FOR TASTY HUMAN",
    "BEEP BOOP",
    "BOT APPETIT",
    "ALGORITHMS SAY YUM",
    "THIS INGREDIENT IS CRUCIAL",
    "96.5% CHANCE DISH IS EDIBLE",
    "HOT FOOD FROM A COLD-HEARTED MACHINE",
    "THIS WOULD BE EASIER IF I COULD TASTE",
    "THIS WOULD BE EASIER IF I COULD TASTE",
    "(WHIRR)",
    "BADA BING!",
    "MAMA MIA!",
)